import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ShareActions } from "@/components/share-actions";
import { TrustBadges } from "@/components/trust-badges";
import { StatusPill } from "@/components/ui/status-pill";
import { buildTrustBadges, selectedTrustTraitsFromReview, type TrustCounts } from "@/lib/trust-badges";
import { createClient } from "@/lib/supabase/server";

type ProfileRow = { id: string; display_name: string; username: string | null; bio: string | null; city: string | null; area: string | null; created_at: string; successful_swaps_count: number; avatar_url?: string | null; cover_url?: string | null; profile_tagline?: string | null; interests?: string | null; preferred_categories?: string | null; swap_preferences?: string | null; };
type ReviewRow = { id: string; rating: number; comment: string | null; created_at: string; clear_description: boolean; good_communication: boolean; on_time: boolean; respectful_swapper: boolean; reviewer: { display_name: string | null; username: string | null }[] | null; };
const genericProfileMetadata: Metadata = { title: "بروفايل على بدّلها", description: "بروفايل مقايضات وتقييمات على بدّلها." };
const isSafePublicImageUrl = (url: string) => url.startsWith("https://") || url.startsWith("http://");

export async function generateMetadata({ params }: { params: Promise<{ username: string }> }): Promise<Metadata> { const { username } = await params; if (!username) return genericProfileMetadata; const supabase = await createClient(); const { data } = await supabase.from("profiles").select("username,display_name,bio,avatar_url").eq("username", username.toLowerCase()).maybeSingle(); const p = data as Pick<ProfileRow, "username" | "display_name" | "bio" | "avatar_url"> | null; if (!p?.username) return genericProfileMetadata; const n = p.display_name || p.username; const d = p.bio || genericProfileMetadata.description!; const a = p.avatar_url && isSafePublicImageUrl(p.avatar_url) ? p.avatar_url : null; return { title: `${n} على بدّلها`, description: d, openGraph: { title: `${n} على بدّلها`, description: d, type: "profile", images: a ? [{ url: a }] : undefined }, twitter: { card: a ? "summary_large_image" : "summary", title: `${n} على بدّلها`, description: d, images: a ? [a] : undefined } }; }

export default async function UserProfilePage({ params, searchParams }: { params: Promise<{ username: string }>; searchParams?: Promise<{ reported?: string }> }) {
  const { username } = await params; const query = (await searchParams) ?? {}; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  const { data: profile } = await supabase.from("profiles").select("id,display_name,username,bio,city,area,created_at,successful_swaps_count,avatar_url,cover_url,profile_tagline,interests,preferred_categories,swap_preferences").eq("username", username.toLowerCase()).maybeSingle();
  if (!profile) notFound(); const typed = profile as ProfileRow;
  const [{ data: items }, { count: dealsCount }, { data: reviewsData }, { data: avgRows }] = await Promise.all([
    supabase.from("items").select("id,title,city,area,created_at,item_story,swap_reason,good_for,item_images(image_url,is_primary)").eq("owner_id", typed.id).eq("status", "active").order("created_at", { ascending: false }).limit(6),
    supabase.from("swap_deals").select("id", { count: "exact", head: true }).or(`requester_id.eq.${typed.id},offerer_id.eq.${typed.id}`),
    supabase.from("reviews").select("id,rating,comment,created_at,clear_description,good_communication,on_time,respectful_swapper,reviewer:profiles!reviews_reviewer_id_fkey(display_name,username)").eq("reviewee_id", typed.id).order("created_at", { ascending: false }).limit(3),
    supabase.from("reviews").select("rating,clear_description,good_communication,on_time,respectful_swapper").eq("reviewee_id", typed.id),
  ]);
  const latestReviews = (reviewsData as ReviewRow[] | null) ?? []; const reviewCount = avgRows?.length ?? 0; const averageRating = reviewCount > 0 ? (avgRows ?? []).reduce((s, r) => s + r.rating, 0) / reviewCount : null;
  const trustCounts: TrustCounts = (avgRows ?? []).reduce((acc, row) => ({ clear_description: acc.clear_description + (row.clear_description ? 1 : 0), good_communication: acc.good_communication + (row.good_communication ? 1 : 0), on_time: acc.on_time + (row.on_time ? 1 : 0), respectful_swapper: acc.respectful_swapper + (row.respectful_swapper ? 1 : 0) }), { clear_description: 0, good_communication: 0, on_time: 0, respectful_swapper: 0 });
  const trustBadges = buildTrustBadges({ counts: trustCounts, successfulSwapsCount: typed.successful_swaps_count, includeBeta: true });
  const displayName = typed.display_name || typed.username || "مستخدم"; const location = [typed.city, typed.area].filter(Boolean).join(" - ");

  return <section className="mx-auto max-w-5xl space-y-6 px-4 py-8">
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="h-36 w-full bg-gradient-to-r from-stone-200 to-amber-100">{typed.cover_url ? <Image src={typed.cover_url} alt="cover" width={1200} height={240} className="h-full w-full object-cover" /> : null}</div><div className="p-5"><div className="-mt-16 mb-3">{typed.avatar_url ? <Image src={typed.avatar_url} alt={displayName} width={96} height={96} className="h-24 w-24 rounded-full border-4 border-white object-cover" /> : <div className="flex h-24 w-24 items-center justify-center rounded-full border-4 border-white bg-stone-100 text-2xl font-bold">{displayName.charAt(0)}</div>}</div><h1 className="text-2xl font-bold">{displayName}</h1><p className="text-stone-600">@{typed.username}</p>{typed.profile_tagline ? <p className="mt-1 text-sm text-stone-700">{typed.profile_tagline}</p> : null}<p className="mt-2 text-sm text-stone-600">{location || "لسه مكملش بيانات المكان"}</p>{typed.bio ? <p className="mt-2 text-stone-700">{typed.bio}</p> : null}<p className="mt-2 text-xs text-stone-500">عضو من {new Date(typed.created_at).toLocaleDateString("ar-EG")}</p></div></div>

    <div className="rounded-2xl border bg-white p-4"><p className="mb-2 text-sm text-stone-700">شارك البروفايل مع حد ممكن يلاقي عنده حاجة مناسبة.</p>{typed.username ? <ShareActions label="شارك البروفايل" title={`${displayName} على بدّلها`} text="شوف بروفايل المقايضات والتقييمات على بدّلها." urlPath={`/users/${typed.username}`} /> : null}</div>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border bg-stone-50 p-4"><p className="text-sm text-stone-600">الحاجات المتاحة</p><p className="text-2xl font-bold">{items?.length ?? 0}</p></div><div className="rounded-xl border bg-stone-50 p-4"><p className="text-sm text-stone-600">مقايضات مكتملة</p><p className="text-2xl font-bold">{typed.successful_swaps_count}</p></div><div className="rounded-xl border bg-stone-50 p-4"><p className="text-sm text-stone-600">كل التقييمات</p><p className="text-2xl font-bold">{reviewCount}</p></div><div className="rounded-xl border bg-stone-50 p-4"><p className="text-sm text-stone-600">متوسط التقييم</p><p className="text-2xl font-bold">{averageRating ? averageRating.toFixed(1) : "-"}</p><p className="text-xs text-stone-500">صفقات مقبولة: {dealsCount ?? 0}</p></div></div>
    <div className="space-y-2 rounded-2xl border bg-white p-4"><h2 className="text-base font-semibold">إشارات الثقة</h2><TrustBadges badges={trustBadges} /></div>

    {query.reported === "1" ? <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-emerald-800">تم إرسال البلاغ. شكرًا إنك ساعدتنا نحافظ على التجربة.</p> : null}
    {user && user.id !== typed.id ? <Link href={`/report?username=${encodeURIComponent(username)}&returnTo=${encodeURIComponent(`/users/${username}`)}`} className="text-sm text-stone-600 hover:underline">بلّغ عن المستخدم</Link> : null}

    <div className="rounded-2xl border bg-white p-4"><h2 className="text-xl font-semibold">بيحب يبدّل إيه؟</h2>{typed.interests || typed.preferred_categories || typed.swap_preferences ? <div className="mt-2 space-y-2 text-stone-700">{typed.interests ? <p><span className="font-medium">اهتماماته:</span> {typed.interests}</p> : null}{typed.preferred_categories ? <p><span className="font-medium">الفئات المفضلة:</span> {typed.preferred_categories}</p> : null}{typed.swap_preferences ? <p><span className="font-medium">تفضيلاته:</span> {typed.swap_preferences}</p> : null}</div> : <p className="mt-2 text-stone-600">لسه ما كتبش اهتماماته في المقايضة.</p>}</div>

    <div className="space-y-3"><h2 className="text-xl font-semibold">آراء الناس بعد المقايضة</h2><p className="text-sm text-stone-600">الآراء دي بتظهر بعد مقايضات مكتملة فقط.</p><p className="text-sm text-stone-700">متوسط التقييم: {averageRating ? averageRating.toFixed(1) : "-"} • عدد التقييمات: {reviewCount}</p>{latestReviews.length ? latestReviews.map((review) => { const reviewer = review.reviewer?.[0]; const selectedSignals = selectedTrustTraitsFromReview(review); return <article key={review.id} className="rounded-xl border bg-white p-4"><p className="text-sm text-stone-500">{new Date(review.created_at).toLocaleDateString("ar-EG")}</p><p className="font-semibold">{reviewer?.display_name ?? reviewer?.username ?? "مستخدم"} • {review.rating}/5</p>{review.comment ? <p className="mt-1 text-sm text-stone-700">{review.comment}</p> : null}{selectedSignals.length ? <div className="mt-2 flex flex-wrap gap-1.5">{selectedSignals.map((signal) => <span key={signal} className="rounded-full border border-stone-200 bg-stone-50 px-2 py-0.5 text-[11px] text-stone-600">{signal}</span>)}</div> : null}</article>; }) : <p className="rounded-xl border bg-white p-4 text-stone-600">لسه مفيش تقييمات.</p>}</div>

    <div className="space-y-3"><h2 className="text-xl font-semibold">الحاجات المتاحة منه</h2>{items?.length ? <div className="grid gap-3 sm:grid-cols-2">{items.map((item) => { const image = Array.isArray((item as { item_images?: { image_url: string; is_primary: boolean }[] }).item_images) ? (item as { item_images?: { image_url: string; is_primary: boolean }[] }).item_images?.find((img) => img.is_primary)?.image_url ?? (item as { item_images?: { image_url: string; is_primary: boolean }[] }).item_images?.[0]?.image_url : null; return <Link key={item.id} href={`/items/${item.id}`} className="rounded-xl border bg-white p-3">{image ? <Image src={image} alt={item.title} width={320} height={180} className="mb-2 h-36 w-full rounded-lg object-cover" /> : null}<div className="mb-1 flex flex-wrap gap-1">{(item as { item_story?: string | null; swap_reason?: string | null; good_for?: string | null }).item_story || (item as { swap_reason?: string | null }).swap_reason || (item as { good_for?: string | null }).good_for ? <StatusPill tone="pending">ليها حكاية</StatusPill> : null}</div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-stone-600">{[item.city, item.area].filter(Boolean).join(" - ") || "بدون موقع"}</p></Link>; })}</div> : <p className="rounded-xl border bg-white p-4 text-stone-600">لسه مفيش حاجات متاحة للمقايضة.</p>}{user?.id === typed.id ? <Link href="/items/new" className="inline-flex rounded-xl border px-4 py-2 text-sm">اعرض حاجة جديدة</Link> : null}</div>
  </section>;
}
