import Link from "next/link";
import type { Route } from "next";
import { redirect } from "next/navigation";
import { AppIcon, type AppIconName } from "@/components/ui/app-icon";
import { Button } from "@/components/ui/button";
import { CountBadge } from "@/components/ui/product-primitives";
import { StatusBadge } from "@/components/ui/status-badge";
import { HeroPanel, InlineNotice, PageSection, SoftPanel, SurfaceCard } from "@/components/ui/surfaces";
import { PageShell } from "@/components/page-shell";
import { createClient } from "@/lib/supabase/server";
import { markAllNotificationsRead, markNotificationRead } from "./actions";
// keep types/logic
 type NotificationType = "offer_received"|"offer_thinking"|"offer_accepted"|"offer_soft_rejected"|"offer_redirected"|"deal_created"|"deal_completed"|"deal_cancelled"|"report_update"|"system";
 type NotificationRow = {id:string;type:NotificationType;title:string;body:string|null;item_id:string|null;offer_id:string|null;deal_id:string|null;read_at:string|null;created_at:string};
 type Tone = "active"|"warning"|"success"|"muted";
 const notificationVisuals: Record<NotificationType, { label: string; icon: AppIconName; tone: Tone }> = {offer_received:{label:"عرض جديد",icon:"offer",tone:"active"},offer_thinking:{label:"محتاج تفكير",icon:"clock",tone:"muted"},offer_accepted:{label:"عرض اتقبل",icon:"check",tone:"success"},offer_soft_rejected:{label:"العرض ما ظبطش",icon:"warning",tone:"warning"},offer_redirected:{label:"باب تاني",icon:"forward",tone:"active"},deal_created:{label:"صفقة جديدة",icon:"deal",tone:"active"},deal_completed:{label:"مقايضة تمت",icon:"check",tone:"success"},deal_cancelled:{label:"صفقة اتلغت",icon:"warning",tone:"warning"},report_update:{label:"تحديث بلاغ",icon:"report",tone:"muted"},system:{label:"تنبيه من النظام",icon:"bell",tone:"muted"}};
 const getTargetLink=(n:NotificationRow):Route|null=>n.deal_id?`/deals/${n.deal_id}` as Route:n.offer_id?`/offers/${n.offer_id}` as Route:n.item_id?`/items/${n.item_id}` as Route:null;
 const getDateBucket=(c:string)=>{const cd=new Date(c),now=new Date();const st=new Date(now.getFullYear(),now.getMonth(),now.getDate());const sc=new Date(cd.getFullYear(),cd.getMonth(),cd.getDate());const d=Math.round((st.getTime()-sc.getTime())/86400000); if(d<=0)return"النهارده" as const; if(d===1)return"امبارح" as const; return "أقدم" as const;};
 const chipClass=(isActive:boolean)=>`rounded-full border px-3 py-1.5 text-sm transition ${isActive?"border-clay bg-app-accent-soft text-app-text-primary":"border-app-border bg-app-surface text-app-text-secondary"}`;
 export default async function NotificationsPage({searchParams}:{searchParams?: Promise<{ filter?: string; updated?: string }>}){const query=(await searchParams)??{}; const filter=query.filter==="unread"?"unread":"all"; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login?next=/notifications"); const qb=supabase.from("notifications").select("id,type,title,body,item_id,offer_id,deal_id,read_at,created_at").order("created_at", { ascending: false }).limit(50); const {data}=filter==="unread"?await qb.is("read_at",null):await qb; const notifications=(data??[]) as NotificationRow[]; const unreadCount=notifications.filter((n)=>!n.read_at).length; const grouped=notifications.reduce<Record<"النهارده"|"امبارح"|"أقدم",NotificationRow[]>>((a,n)=>{a[getDateBucket(n.created_at)].push(n);return a;},{النهارده:[],امبارح:[],أقدم:[]});
 return <PageShell title="الإشعارات"><PageSection><HeroPanel><h1 className="text-2xl font-semibold">الإشعارات</h1><p className="mt-1 text-sm text-app-text-secondary">الإشعارات بتجمع عروضك وصفقاتك وبلاغاتك، لكنها مش Push Notifications لسه.</p>{unreadCount>0?<p className="mt-2 text-sm">غير مقروءة: <CountBadge count={unreadCount} /></p>:null}</HeroPanel>{query.updated==="read_all"?<InlineNotice tone="accent">تم تعليم كل الإشعارات كمقروءة.</InlineNotice>:null}<SoftPanel className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><Link href="/notifications" className={chipClass(filter==="all")}>الكل</Link><Link href="/notifications?filter=unread" className={chipClass(filter==="unread")}>غير مقروءة</Link></div>{unreadCount>0?<form action={markAllNotificationsRead}><Button variant="secondary" size="sm">علّم الكل كمقروء</Button></form>:null}</SoftPanel>{notifications.length===0?<SoftPanel><p className="font-semibold">{filter==="unread"?"مفيش جديد دلوقتي.":"لسه مفيش إشعارات."}</p></SoftPanel>:<div className="space-y-4">{(["النهارده","امبارح","أقدم"] as const).map((g)=>grouped[g].length>0?<section key={g} className="space-y-2"><h2 className="text-sm font-semibold text-app-text-muted">{g}</h2><div className="space-y-2">{grouped[g].map((n)=>{const link=getTargetLink(n);const v=notificationVisuals[n.type];const isUnread=!n.read_at;return <SurfaceCard key={n.id} className={isUnread?"border-clay/40 bg-clay/5":""}><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{n.title}</p>{n.body?<p className="text-sm text-app-text-secondary">{n.body}</p>:null}<p className="mt-1 text-xs text-app-text-muted">{new Date(n.created_at).toLocaleString("ar-EG")}</p></div><div className="flex items-center gap-2"><StatusBadge variant={v.tone}>{v.label}</StatusBadge><AppIcon name={v.icon} className="h-4 w-4 text-app-text-muted" /></div></div><div className="mt-2 flex gap-3 text-sm">{link?<Link href={link} className="text-clay">افتح</Link>:<span className="text-app-text-muted">التفاصيل مش متاحة دلوقتي</span>}{isUnread?<form action={markNotificationRead}><input type="hidden" name="notification_id" value={n.id} /><input type="hidden" name="filter" value={filter} /><button className="underline">علّم كمقروء</button></form>:null}</div></SurfaceCard>;})}</div></section>:null)}</div>}</PageSection></PageShell>; }
