"use client";
import { useState } from "react";
import { AppIcon } from "@/components/ui/app-icon";
import { Button } from "@/components/ui/button";
import { Field, HelperText, Label, Select, Textarea } from "@/components/ui/form";
import { SoftPanel, SurfaceCard } from "@/components/ui/surfaces";
import { acceptOffer, markOfferThinking, redirectOffer, softRejectOffer } from "./actions";
type ResponseMode = "accept" | "thinking" | "soft_reject" | "redirect";
const decisionOptions=[{ key:"accept",title:"اقبل الاقتراح",hint:"غرفة التنسيق تفتح فورًا.",icon:"check"},{ key:"thinking",title:"محتاج أفكر",hint:"الطرف التاني يعرف إنك محتاج وقت.",icon:"clock"},{ key:"soft_reject",title:"الاقتراح مش مناسب",hint:"تقفله بلطف من غير ما تفتح تنسيق.",icon:"warning"},{ key:"redirect",title:"افتح باب تاني",hint:"تسيب له مساحة يرجع باقتراح مختلف.",icon:"forward"}] as const;
const redirectChoices=[{value:"offer_another_item",label:"اعرض حاجة تانية"},{value:"ask_for_different_item",label:"بدور على نوع مختلف"},{value:"update_preferences",label:"وضّحلي اختياراتك أكتر"}];
export function OfferResponsePanel({ offerId }: { offerId: string }) {const [mode,setMode]=useState<ResponseMode|null>(null);return <SurfaceCard className="space-y-4 p-4 md:p-5"><div><h2 className="text-lg font-semibold">اختار ردك على الاقتراح</h2><p className="text-sm text-app-text-muted">قرارك يحدد هل القيمة دي هتتحول لتنسيق، ولا تحتاج بابًا مختلفًا.</p></div><div className="grid gap-2 sm:grid-cols-2">{decisionOptions.map((option)=>{const active=mode===option.key;return <button key={option.key} type="button" onClick={()=>setMode(option.key)} className={`rounded-xl border p-3 text-right transition ${active?"border-clay bg-clay/5":"border-stone-200 bg-white hover:border-stone-300"}`}><p className="flex items-center gap-2 font-semibold"><AppIcon name={option.icon} className="size-4 text-clay" />{option.title}</p><p className="mt-1 text-sm text-app-text-muted">{option.hint}</p></button>;})}</div>
{mode==="accept"?<form action={acceptOffer}><input type="hidden" name="offerId" value={offerId}/><SoftPanel className="space-y-3"><p className="font-semibold">تأكيد القبول</p><HelperText>بعد القبول، الاقتراح يتحول لمسار تنسيق.</HelperText><Button type="submit" variant="primary" size="sm">اقبل الاقتراح</Button></SoftPanel></form>:null}
{mode==="thinking"?<form action={markOfferThinking}><input type="hidden" name="offerId" value={offerId}/><SoftPanel className="space-y-3"><p className="font-semibold">خلّيه محتاج تفكير</p><Field><Label htmlFor="thinking-note" optional>ملاحظة بسيطة</Label><Textarea id="thinking-note" name="note" placeholder="شكراً على العرض، محتاج أفكر شوية." /></Field><Button type="submit" variant="secondary" size="sm">خلّيه محتاج تفكير</Button></SoftPanel></form>:null}
{mode==="soft_reject"?<form action={softRejectOffer}><input type="hidden" name="offerId" value={offerId}/><SoftPanel className="space-y-3"><p className="font-semibold">اقفل الاقتراح بلطف</p><Field><Label htmlFor="reject-note" optional>سبب بسيط</Label><Textarea id="reject-note" name="note" placeholder="شكراً، بس العرض مش مناسب ليا دلوقتي."/></Field><Button type="submit" variant="secondary" size="sm">اقفله بلطف</Button></SoftPanel></form>:null}
{mode==="redirect"?<form action={redirectOffer}><input type="hidden" name="offerId" value={offerId}/><SoftPanel className="space-y-3"><p className="font-semibold">افتح باب تاني</p><Field><Label htmlFor="redirectType" required>نوع الباب التاني</Label><Select id="redirectType" name="redirectType" defaultValue=""><option value="" disabled>اختار نوع الباب التاني</option>{redirectChoices.map((c)=><option key={c.value} value={c.value}>{c.label}</option>)}</Select></Field><Field><Label htmlFor="redirect-note" optional>ملاحظة</Label><Textarea id="redirect-note" name="note" placeholder="ممكن تبعت حاجة أقرب لاحتياجي." /></Field><Button type="submit" size="sm">افتح باب تاني</Button></SoftPanel></form>:null}
</SurfaceCard>; }
