"use client";

import { useFormStatus } from "react-dom";

function SubmitButton() {
  const { pending } = useFormStatus();
  return <button type="submit" disabled={pending} className="rounded-xl bg-clay px-4 py-2 text-white disabled:opacity-60">{pending ? "جاري الحفظ..." : "حفظ التعديلات"}</button>;
}

export function ItemEditForm({ item, categories, action }: { item: { id: string; title: string; category_id: string | null; description: string | null; condition: string; condition_notes: string | null; city: string | null; area: string | null; desire_mode: string; desire_text: string | null; item_story: string | null; swap_reason: string | null; good_for: string | null; wanted_tags: string; }; categories: Array<{ id: string; name_ar: string }>; action: (formData: FormData) => Promise<void>; }) {
  return <form action={action} className="space-y-3 rounded-xl border bg-white p-4"><input type="hidden" name="item_id" value={item.id} /><p className="rounded-lg bg-amber-50 p-2 text-sm text-amber-900">تعديل الصور جاي بعدين. دلوقتي تقدر تعدّل تفاصيل الإعلان.</p><input name="title" defaultValue={item.title} required className="w-full rounded-xl border px-3 py-2" /><select name="category_id" defaultValue={item.category_id ?? ""} className="w-full rounded-xl border px-3 py-2"><option value="">بدون تصنيف</option>{categories.map((c)=><option key={c.id} value={c.id}>{c.name_ar}</option>)}</select><textarea name="description" defaultValue={item.description ?? ""} className="w-full rounded-xl border px-3 py-2" /><select name="condition" defaultValue={item.condition} className="w-full rounded-xl border px-3 py-2"><option value="almost_new">جديد تقريبًا</option><option value="good_used">مستخدم بحالة كويسة</option><option value="minor_issues">فيه عيوب بسيطة</option><option value="needs_repair">محتاج تصليح / عارف حالته</option></select><textarea name="condition_notes" defaultValue={item.condition_notes ?? ""} className="w-full rounded-xl border px-3 py-2" /><input name="city" defaultValue={item.city ?? ""} className="w-full rounded-xl border px-3 py-2" /><input name="area" defaultValue={item.area ?? ""} className="w-full rounded-xl border px-3 py-2" />
  <textarea name="item_story" maxLength={600} defaultValue={item.item_story ?? ""} placeholder="قصة الحاجة" className="w-full rounded-xl border px-3 py-2" />
  <textarea name="swap_reason" maxLength={240} defaultValue={item.swap_reason ?? ""} placeholder="ليه حابب تبدّلها دلوقتي؟" className="w-full rounded-xl border px-3 py-2" />
  <textarea name="good_for" maxLength={240} defaultValue={item.good_for ?? ""} placeholder="مناسبة لمين؟" className="w-full rounded-xl border px-3 py-2" />
  <select name="desire_mode" defaultValue={item.desire_mode} className="w-full rounded-xl border px-3 py-2"><option value="specific">بدور على حاجة معينة</option><option value="flexible">مرن في نوع الحاجة</option><option value="surprise">مفتوح لأي حاجة مناسبة</option></select><textarea name="desire_text" defaultValue={item.desire_text ?? ""} className="w-full rounded-xl border px-3 py-2" /><input name="wanted_tags" defaultValue={item.wanted_tags} placeholder="مثال: كرسي, مكتب, نباتات" className="w-full rounded-xl border px-3 py-2" /><SubmitButton /></form>;
}
