import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { addItemToDrop, createDrop, featureStoryItem, removeItemFromDrop, unfeatureStoryItem, updateDrop } from "@/app/admin/drops/actions";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeading } from "@/components/ui/page-heading";
import { isCurrentUserAdmin } from "@/lib/admin";
import { createClient } from "@/lib/supabase/server";

type MaybeArray<T> = T | T[] | null | undefined;

function firstOrNull<T>(value: MaybeArray<T>): T | null {
  if (!value) return null;
  return Array.isArray(value) ? value[0] ?? null : value;
}

export default async function AdminDropsPage({searchParams}:{searchParams:Promise<{ok?:string;error?:string}>}){const params=await searchParams;const s=await createClient();const {data:{user}}=await s.auth.getUser(); if(!user) redirect('/login?next=/admin/drops'); if(!(await isCurrentUserAdmin(s))) notFound();
const [{data:featured},{data:candidates},{data:drops}] = await Promise.all([
 s.from('featured_story_items').select('item_id,sort_order,curator_note,items!inner(id,title)').order('sort_order'),
 s.from('items').select('id,title,item_story,swap_reason,good_for,profiles!items_owner_id_fkey(display_name,username)').eq('status','active').or('item_story.not.is.null,swap_reason.not.is.null,good_for.not.is.null').order('created_at',{ascending:false}).limit(20),
 s.from('creator_drops').select('id,slug,title,drop_type,creator_name,intro_copy,status,creator_drop_items(sort_order,item_id,items!inner(title))').order('created_at',{ascending:false})]);
const featuredRows = (featured ?? []) as Array<{ item_id:string; sort_order:number; curator_note:string|null; items:MaybeArray<{ id:string; title:string }> }>;
const candidateRows = (candidates ?? []) as Array<{ id:string; title:string }>;
const dropRows = (drops ?? []) as Array<{ id:string; slug:string; title:string; drop_type:string; creator_name:string|null; intro_copy:string; status:string; creator_drop_items:{ item_id:string; items:MaybeArray<{ title:string }> }[]|null }>;
return <section className='mx-auto max-w-6xl space-y-4 px-4 py-10'><PageHeading title='إدارة الدروب والحكايات' subtitle='تنسيق يدوي للطبقة القصصية المميزة.'/>{params.ok?<Alert variant='success'>تم التنفيذ.</Alert>:null}{params.error?<Alert variant='danger'>حصل خطأ في المدخلات أو الحفظ.</Alert>:null}
<Card><CardHeader><CardTitle>Featured Story Items</CardTitle></CardHeader><CardContent className='space-y-3'>{featuredRows.map((f)=>{ const linkedItem = firstOrNull(f.items); return <div key={f.item_id} className='flex items-center gap-2 text-sm'><Link className='underline' href={`/items/${f.item_id}`}>{linkedItem?.title ?? "عنصر"}</Link><span>#{f.sort_order}</span><form action={unfeatureStoryItem}><input type='hidden' name='item_id' value={f.item_id}/><Button size='sm' variant='secondary'>إزالة</Button></form></div>;})}<div className='grid gap-2'>{candidateRows.map((i)=><form key={i.id} action={featureStoryItem} className='flex flex-wrap items-center gap-2 rounded border p-2 text-sm'><input type='hidden' name='item_id' value={i.id}/><span className='font-medium'>{i.title}</span><input name='sort_order' type='number' defaultValue={0} className='w-20 rounded border px-2 py-1'/><input name='curator_note' maxLength={240} placeholder='ملاحظة' className='rounded border px-2 py-1'/><Button size='sm'>تمييز</Button></form>)}</div></CardContent></Card>
<Card><CardHeader><CardTitle>Creator Drops</CardTitle></CardHeader><CardContent className='space-y-4'><form action={createDrop} className='grid gap-2 rounded border p-3 md:grid-cols-2'><input name='slug' placeholder='slug' className='rounded border px-2 py-1'/><input name='title' placeholder='title' className='rounded border px-2 py-1'/><input name='drop_type' placeholder='artist_drop' className='rounded border px-2 py-1'/><input name='creator_name' placeholder='creator' className='rounded border px-2 py-1'/><select name='status' className='rounded border px-2 py-1'><option value='draft'>draft</option><option value='published'>published</option></select><textarea name='intro_copy' placeholder='intro' className='rounded border px-2 py-1 md:col-span-2'/><Button>إنشاء دروب</Button></form>
{dropRows.map((d)=><div key={d.id} className='rounded border p-3 space-y-2'><form action={updateDrop} className='grid gap-2 md:grid-cols-2'><input type='hidden' name='drop_id' value={d.id}/><input name='title' defaultValue={d.title} className='rounded border px-2 py-1'/><input name='slug' defaultValue={d.slug} className='rounded border px-2 py-1' disabled/><input name='drop_type' defaultValue={d.drop_type} className='rounded border px-2 py-1'/><input name='creator_name' defaultValue={d.creator_name??''} className='rounded border px-2 py-1'/><select name='status' defaultValue={d.status} className='rounded border px-2 py-1'><option value='draft'>draft</option><option value='published'>published</option></select><textarea name='intro_copy' defaultValue={d.intro_copy} className='rounded border px-2 py-1 md:col-span-2'/><Button size='sm'>حفظ</Button></form><form action={addItemToDrop} className='flex gap-2 text-sm'><input type='hidden' name='drop_id' value={d.id}/><input name='item_id' placeholder='item uuid' className='flex-1 rounded border px-2 py-1'/><input name='sort_order' type='number' defaultValue={0} className='w-20 rounded border px-2 py-1'/><Button size='sm' variant='secondary'>إضافة</Button></form>{(d.creator_drop_items??[]).map((row)=>{ const linkedItem = firstOrNull(row.items); return <form key={row.item_id} action={removeItemFromDrop} className='flex items-center gap-2 text-sm'><input type='hidden' name='drop_id' value={d.id}/><input type='hidden' name='item_id' value={row.item_id}/><span>{linkedItem?.title ?? "عنصر"}</span><Button size='sm' variant='secondary'>إزالة</Button></form>;})}</div>)}</CardContent></Card></section>}
