import type { Route } from "next";
import { redirect } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { ButtonLink } from "@/components/ui/button";
import { CountBadge, MetricPill, TrustChip } from "@/components/ui/product-primitives";
import { HeroPanel, HighlightPanel, InlineNotice, PageSection, SoftPanel, SurfaceCard } from "@/components/ui/surfaces";
import { isCurrentUserAdmin } from "@/lib/admin";
import { createClient } from "@/lib/supabase/server";

type OfferStatus = "pending" | "thinking" | "accepted";
export default async function DashboardPage() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?next=/dashboard");
const [{data:profile},{count:activeItemsCount},{data:receivedOffers},{data:sentOffers},{count:dealsCount},{count:completedDealsCount},{count:pendingConfirmationsCount},{count:unreadNotificationsCount},unreadMessagesResult,isAdmin] = await Promise.all([supabase.from("profiles").select("display_name,username,bio,city,area").eq("id", user.id).maybeSingle(),supabase.from("items").select("id", { count: "exact", head: true }).eq("owner_id", user.id).eq("status", "active"),supabase.from("offers").select("status").eq("receiver_id", user.id),supabase.from("offers").select("status").eq("sender_id", user.id),supabase.from("swap_deals").select("id", { count: "exact", head: true }).or(`requester_id.eq.${user.id},offerer_id.eq.${user.id}`),supabase.from("swap_deals").select("id", { count: "exact", head: true }).or(`requester_id.eq.${user.id},offerer_id.eq.${user.id}`).eq("status", "completed"),supabase.from("swap_deals").select("id", { count: "exact", head: true }).or(`requester_id.eq.${user.id},offerer_id.eq.${user.id}`).eq("status", "completed_pending_confirmation"),supabase.from("notifications").select("id", { count: "exact", head: true }).eq("user_id", user.id).is("read_at", null),supabase.rpc("get_unread_deal_messages_count"),isCurrentUserAdmin(supabase)]);
const unreadMessagesCount = unreadMessagesResult.error ? 0 : Number(unreadMessagesResult.data ?? 0); const received=(receivedOffers??[]).map((o)=>o.status as OfferStatus); const sent=(sentOffers??[]).map((o)=>o.status as OfferStatus); const username=profile?.username??null; const profileComplete=Boolean(username&&profile?.city&&profile?.area&&profile?.bio); const receivedNeedsResponseCount=received.filter((s)=>s==="pending"||s==="thinking").length; const sentFollowupCount=sent.filter((s)=>s==="accepted"||s==="thinking"||s==="pending").length; const attentionItems: Array<{key:string;title:string;count:number;href:Route;cta:string}>=[{key:"offers",title:"عروض محتاجة رد",count:receivedNeedsResponseCount,href:"/dashboard/offers/received",cta:"افتح العروض"},{key:"deals",title:"صفقات مستنية تأكيد",count:pendingConfirmationsCount??0,href:"/deals",cta:"افتح الصفقات"},{key:"messages",title:"رسائل غير مقروءة",count:unreadMessagesCount,href:"/messages",cta:"افتح الرسائل"},{key:"notifications",title:"إشعارات غير مقروءة",count:unreadNotificationsCount??0,href:"/notifications",cta:"افتح الإشعارات"}]; const urgent=attentionItems.filter((i)=>i.count>0);
return <PageShell title="حسابي"><PageSection><HeroPanel><h1 className="text-2xl font-semibold">حسابي</h1><p className="mt-1 text-sm text-app-text-secondary">مركز حسابك: راجع المهم دلوقتي، تابع نشاطك ورسائلك، وعدّل بروفايلك.</p><div className="mt-3 flex flex-wrap gap-2"><TrustChip>{profile?.display_name ?? "مستخدم"}</TrustChip>{username ? <TrustChip tone="info">@{username}</TrustChip> : <TrustChip tone="meta">كمّل اسم المستخدم</TrustChip>}</div></HeroPanel>
<SurfaceCard className="space-y-3"><h2 className="text-lg font-semibold">المهم دلوقتي {urgent.length>0?<CountBadge count={urgent.length} />:null}</h2>{urgent.length>0?<div className="grid gap-3 md:grid-cols-2">{urgent.map((i)=><HighlightPanel key={i.key} className="flex items-center justify-between gap-2"><div><p className="font-medium">{i.title}</p><p className="text-sm">{i.count}</p></div><ButtonLink href={i.href} size="sm" variant="secondary">{i.cta}</ButtonLink></HighlightPanel>)}</div>:<InlineNotice tone="accent">مفيش حاجة مستعجلة دلوقتي. <ButtonLink href="/items" variant="quiet" size="sm">شوف السوق</ButtonLink></InlineNotice>}</SurfaceCard>
<div className="grid gap-3 md:grid-cols-2"><SoftPanel><p className="font-semibold">حاجاتي</p><MetricPill label="نشط" value={activeItemsCount ?? 0} /><div className="mt-2"><ButtonLink href="/dashboard/items" size="sm" variant="secondary">إدارة حاجاتي</ButtonLink></div></SoftPanel><SoftPanel><p className="font-semibold">عروض وصلتني</p><p className="text-sm">إجمالي {received.length} • محتاجة رد {receivedNeedsResponseCount}</p><div className="mt-2"><ButtonLink href="/dashboard/offers/received" size="sm" variant="secondary">افتح العروض</ButtonLink></div></SoftPanel><SoftPanel><p className="font-semibold">عروض بعتها</p><p className="text-sm">إجمالي {sent.length} • متابعة {sentFollowupCount}</p><div className="mt-2"><ButtonLink href="/dashboard/offers/sent" size="sm" variant="secondary">افتح العروض</ButtonLink></div></SoftPanel><SoftPanel><p className="font-semibold">صفقاتي</p><p className="text-sm">إجمالي {dealsCount ?? 0} • تمت {completedDealsCount ?? 0} • مستنية تأكيد {pendingConfirmationsCount ?? 0}</p><div className="mt-2"><ButtonLink href="/deals" size="sm" variant="secondary">افتح الصفقات</ButtonLink></div></SoftPanel></div>
<SurfaceCard><h2 className="text-lg font-semibold">حسابي والثقة</h2><p className="mt-1 text-sm text-app-text-secondary">كل ما بياناتك تكون أوضح، فرص المقايضة المناسبة بتزيد.</p>{!profileComplete?<InlineNotice tone="warning" className="mt-3">كمّل بروفايلك عشان يبقى واضح ومقنع.</InlineNotice>:null}<div className="mt-3 flex gap-2"><ButtonLink href="/profile" variant="secondary" size="sm">تعديل بروفايلك</ButtonLink>{username?<ButtonLink href={`/users/${username}` as Route} variant="outline" size="sm">شوف بروفايلك العام</ButtonLink>:null}</div></SurfaceCard>
<SoftPanel><h2 className="text-lg font-semibold">الدعم والأدوات</h2><div className="mt-2 flex flex-wrap gap-2"><ButtonLink href="/feedback" variant="outline" size="sm">ابعت رأيك</ButtonLink><ButtonLink href="/dashboard/feedback" variant="outline" size="sm">شوف feedback اللي بعته</ButtonLink><ButtonLink href="/dashboard/reports" variant="outline" size="sm">بلاغاتي</ButtonLink>{isAdmin?<ButtonLink href="/admin/reports" variant="outline" size="sm">مراجعة البلاغات</ButtonLink>:null}<ButtonLink href="/install" variant="secondary" size="sm">نزّل تِسوى على موبايلك</ButtonLink></div></SoftPanel>
</PageSection></PageShell>; }
